basePath: /
definitions:
  models.Passages:
    properties:
      author:
        type: string
      category:
        description: 默认长度为255
        type: string
      content:
        description: 如果content字段为空或默认值，将不会返回改数据
        type: string
      created_at:
        description: omitempty 前端可以不用传入该字段，自动生成默认值，返回值如果为空，则不会返回该字段。
        type: string
      description:
        type: string
      id:
        description: primary_key定义主键   AUTO_INCREMENT定义自增
        type: integer
      img_link:
        description: 忽略这个字段
        type: string
      is_delete:
        type: integer
      look:
        description: 如果look_num的值为0  则不会返回该字段
        type: integer
      tag:
        description: 类型为varchar  最大100 列名为 `tag`
        type: string
      title:
        description: 不为空，且唯一
        type: string
      updated_at:
        type: string
    type: object
host: localhost:9001
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /web/passage/add:
    post:
      consumes:
      - application/json
      description: 添加文章接口
      parameters:
      - description: test
        in: body
        name: test
        required: true
        schema:
          type: string
      - description: 请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Passages'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: int
      summary: 添加文章
      tags:
      - 类别
  /web/passage/list:
    get:
      consumes:
      - application/json
      description: 描述信息
      parameters:
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 文章列表
      tags:
      - 类别
swagger: "2.0"
